service: lassistant

# 플러그인
plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  TELEGRAM: ${file(./config/config.js):TELEGRAM}
  NAVER: ${file(./config/config.js):NAVER}
  KAKAO: ${file(./config/config.js):KAKAO}
  schedules: # info: Health Checker!
    dev: false
    production:
      rate: rate(4 minutes)
      enabled: false
      description: "Health Checker"
      input:
        healthCheck: true

# 제공자
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-2'}
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 10
  versionFunctions: false # optional, default is true

  environment:
    REGION: ${opt:region, 'ap-northeast-2'}
    STAGE: ${self:provider.stage}
    TELEGRAM_TOKEN: ${self:custom.TELEGRAM.${self:provider.stage}.TELEGRAM_TOKEN}
    TELEGRAM_CHAT_ID: ${self:custom.TELEGRAM.${self:provider.stage}.TELEGRAM_CHAT_ID}
    TELEGRAM_OWNER_CHAT_ID: ${self:custom.TELEGRAM.${self:provider.stage}.TELEGRAM_OWNER_CHAT_ID}
    TELEGRAM_BOT_NAME: ${self:custom.TELEGRAM.${self:provider.stage}.TELEGRAM_BOT_NAME}
    NAVER_CLIENT_ID: ${self:custom.NAVER.${self:provider.stage}.NAVER_CLIENT_ID}
    NAVER_CLIENT_SECRET: ${self:custom.NAVER.${self:provider.stage}.NAVER_CLIENT_SECRET}
    KAKAO_REST_API_KEY: ${self:custom.KAKAO.${self:provider.stage}.KAKAO_REST_API_KEY}
    LOCALE: 'ko-KR'
    TIMEZONE: 'Asia/Seoul'
    TZ: 'Asia/Seoul'

package:
  individually: true
  exclude:
    - .idea/**
    - package-lock.json
    - package.json
    - node_modules/**
    - test/**
    - .gitmodules
    - .git/**

functions:
  webHook: # Index (web hook)
    handler: src/http/index.handler
    description: Web Hook Handling
    package:
      exclude:
        - src/**
      include:
        - node_modules/**
        - lib/**
        - src/http/**
    events:
      - http:
          path: /
          method: any
          cors: true

  dailyNews: # 매일 아침 뉴스
    handler: src/schedule/dailyNews.handler
    description: DailyNews Scheduler
    package:
      exclude:
        - src/**
      include:
        - node_modules/**
        - lib/**
        - src/schedule/**
    events:
      - schedule:
          rate: cron(0 22 * * ? *)
          enabled: true
