service: lassistant

# 플러그인
plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  ENV: ${file(./env/${self:provider.stage}.json)}

# 제공자
provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  memorySize: 256 # optional, in MB, default is 1024
  timeout: 120 # optional, in seconds, default is 10
  versionFunctions: false # optional, default is true

  environment:
    REGION: ${opt:region, 'ap-northeast-2'}
    STAGE: ${self:provider.stage}
    TELEGRAM_TOKEN: ${self:custom.ENV.TELEGRAM_TOKEN}
    TELEGRAM_CHAT_ID: ${self:custom.ENV.TELEGRAM_CHAT_ID}
    TELEGRAM_OWNER_CHAT_ID: ${self:custom.ENV.TELEGRAM_OWNER_CHAT_ID}
    TELEGRAM_BOT_NAME: ${self:custom.ENV.TELEGRAM_BOT_NAME}
    REDIS_SERVER_HOST: ${self:custom.ENV.REDIS_SERVER_HOST}
    REDIS_SERVER_PORT: ${self:custom.ENV.REDIS_SERVER_PORT}
    REDIS_SERVER_PASSWORD: ${self:custom.ENV.REDIS_SERVER_PASSWORD}
    OPENAI_API_KEY: ${self:custom.ENV.OPENAI_API_KEY}
    LOCALE: 'ko-KR'
    TIMEZONE: 'Asia/Seoul'
    TZ: 'Asia/Seoul'

package:
  individually: true
  exclude:
    - .idea/**
    - yarn.lock
    - package.json
    - test/**
    - .gitmodules
    - .git/**

functions:
  webhook: # 봇 웹훅
    handler: src/handlers/webhook.handler
    description: Webhook Handling
    events:
      - http:
          path: /
          method: any
          cors: true

  dailyNews: # 매일 아침 뉴스
    handler: src/handlers/dailyNews.handler
    description: DailyNews Scheduler
    events:
      - schedule:
          rate: cron(0 22 * * ? *)
          enabled: true
          description: '매일 오전 7시'
