service: lassistant

# 플러그인
plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  ENV: ${file(./env/${self:provider.stage}.json)}
  schedules: # info: Health Checker!
    dev: false
    production:
      rate: rate(4 minutes)
      enabled: false
      description: "Health Checker"
      input:
        healthCheck: true

# 제공자
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 10
  versionFunctions: false # optional, default is true

  environment:
    REGION: ${opt:region, 'ap-northeast-2'}
    STAGE: ${self:provider.stage}
    TELEGRAM_TOKEN: ${self:custom.ENV.TELEGRAM_TOKEN}
    TELEGRAM_CHAT_ID: ${self:custom.ENV.TELEGRAM_CHAT_ID}
    TELEGRAM_OWNER_CHAT_ID: ${self:custom.ENV.TELEGRAM_OWNER_CHAT_ID}
    TELEGRAM_BOT_NAME: ${self:custom.ENV.TELEGRAM_BOT_NAME}
    LOCALE: 'ko-KR'
    TIMEZONE: 'Asia/Seoul'
    TZ: 'Asia/Seoul'

package:
  individually: true
  exclude:
    - .idea/**
    - yarn.lock
    - package.json
    - node_modules/**
    - test/**
    - .gitmodules
    - .git/**

functions:
  webHook: # Index (web hook)
    handler: src/http/index.handler
    description: Web Hook Handling
    package:
      exclude:
        - src/**
      include:
        - node_modules/**
        - lib/**
        - src/http/**
    events:
      - http:
          path: /
          method: any
          cors: true

  dailyNews: # 매일 아침 뉴스
    handler: src/schedule/dailyNews.handler
    description: DailyNews Scheduler
    package:
      exclude:
        - src/**
      include:
        - node_modules/**
        - lib/**
        - src/**
    events:
      - schedule:
          rate: cron(0 22 * * ? *)
          enabled: true
          description: '매일 오전 7시'
